// Plugin generated by ChatGPT

import fs from "node:fs";
import path from "node:path";


/**
 * Recursively return all files below `directory`.
 *
 * For example:
 *     getFiles("someDir")
 * might return:
 *     [
 *         "someDir/someFile",
 *         "someDir/subdir/someOtherFile"
 *     ]
 *
 * Only files are returned, not the subdirectories containing them.
 */
async function getFiles(directory) {
    // `withFileTypes: true` gives us Dirent objects,
    // allowing us to distinguish files from directories.
    const entries = await fs.promises.readdir(
        directory,
        { withFileTypes: true }
    );

    const files = [];

    for (const entry of entries) {
        const entryPath = path.join(
            directory,
            entry.name
        );

        if (entry.isDirectory()) {
            // Recursively explore this subdirectory.
            files.push(
                ...(await getFiles(entryPath))
            );
        } else if (entry.isFile()) {
            // Add regular files to the result.
            files.push(entryPath);
        }
    }

    return files;
}


/**
 * Copy the contents of a directory into the Vite output.
 *
 * The source directory itself is not copied:
 *
 *     src/
 *     ├── A.ogg
 *     └── subdir/
 *         └── B.ogg
 *
 *     dest/
 *
 * becomes:
 *
 *     dest/
 *     ├── A.ogg
 *     └── subdir/
 *         └── B.ogg
 *
 * `reorganize()` is called once for every file with its path relative to `src`
 *  and returns the path that should be used relative to `dest`.
 *
 * For example to rename a file, reorganize("oldFileName") can return "newFileName"
 * or to rename a subdirectory, reorganize("oldSubdirName/fileName") can return "newSubdirName/fileName"
 * or to rename both, reorganize("oldSubdirName/oldFileName") can return "newSubdirName/newFileName"
 */
export default function copyDirContent({
    src,
    dest,
    reorganize = relativePath => relativePath
}) {
    return {
        // Name used by Vite/Rollup when reporting plugin information.
        name: "vite-plugin-copy-dir-content",


        /**
         * Development server
         *
         * Running `vite` without arguments does not produce a `dist` directory.
         * Instead, Vite serves files through its development server.
         *
         * This hook adds middleware to that server.
         * When the browser requests a file under `dest`, we:
         *     1. Find the corresponding source file.
         *     2. Read that source file.
         *     3. Send its contents as the response.
         *
         * Thus:
         *     /newSubdirName/newFileName
         * is served from:
         *     src/oldSubdirName/oldFileName
         */
        configureServer(server) {
            // Resolve `src` relative to Vite's project root.
            const sourceDirectory = path.resolve(
                server.config.root,
                src
            );

            // Add middleware to redirect the browser requests under `dest`
            server.middlewares.use(async (req, res, next) => {
                // A request without a URL cannot be handled.
                if (!req.url) {
                    next();
                    return;
                }

                // Remove the query string from the URL.
                //
                // For example:
                //     /newSubdirName/newFileName?v=123
                // becomes:
                //     /newSubdirName/newFileName
                const requestPath = decodeURIComponent(
                    req.url.split("?")[0]
                );

                // Remove leading slashes so that the result can be
                // compared with paths such as:
                //     newSubdirName/newFileName
                const destinationPath = requestPath.replace(
                    /^\/+/,
                    ""
                );

                // Recursively find all files below the source directory.
                const files = await getFiles(sourceDirectory);

                // Look for the source file whose reorganized path matches the URL requested by the browser.
                for (const sourceFile of files) {
                    // Compute the path relative to `src`.
                    //
                    // Example:
                    //     sourceFile:
                    //         /some/path/oldSubdirName/oldFileName
                    //     sourceDirectory:
                    //         /some/path
                    //     relativePath:
                    //         oldSubdirName/oldFileName
                    const relativePath = path.relative(
                        sourceDirectory,
                        sourceFile
                    );

                    // Let the user decide where the file should appear.
                    //
                    // Example:
                    //     oldSubdirName/oldFileName
                    //                 ↓
                    //     newSubdirName/newFileName
                    const reorganizedPath = reorganize(relativePath);

                    // Combine the destination directory with the reorganized relative path.
                    //
                    // Example:
                    //     <dest>/newSubdirName/newFileName
                    const servedPath = path.posix.join(
                        dest,
                        reorganizedPath
                    );

                    // If the source file does not correspond to the requested URL, move on the next file.
                    if (servedPath !== destinationPath) {
                        continue;
                    }

                    // Otherwise the requested file was found, stream it directly from the source file to the browser response.
                    fs.createReadStream(sourceFile)
                        .on("error", next)
                        .pipe(res);

                    return;
                }

                // If we reached here, this plugin does not handle the request,
                // so let Vite and other middleware process it.
                next();
            });
        },


        /**
         * Production build
         *
         * During `vite build`, Rollup calls `generateBundle`.
         *
         * We:
         *     1. Find all source files.
         *     2. Compute each file's relative path.
         *     3. Reorganize that path.
         *     4. Add the file to the Rollup output.
         *
         * Vite/Rollup then writes the emitted assets into `dist`.
         */
        async generateBundle() {
            // Resolve `src` relative to the project directory.
            const sourceDirectory = path.resolve(
                process.cwd(),
                src
            );

            // Find every file recursively below `src`.
            const files = await getFiles(sourceDirectory);

            for (const sourceFile of files) {
                // Path relative to the source directory.
                const relativePath = path.relative(
                    sourceDirectory,
                    sourceFile
                );

                // Transform the relative path.
                const reorganizedPath = reorganize(relativePath);

                // Build the final path inside the build output.
                //
                // Example:
                //     <dest>/newSubdirName/newFileName
                const outputPath = path.posix.join(
                    dest,
                    reorganizedPath
                );

                // Add the file as a Rollup asset.
                //
                // `fileName` is relative to the build output directory.
                // Vite will therefore write this to:
                //     dist/<dest>/newSubdirName/newFileName
                //
                // Subdirectories will be created by Rollup if they do not already exist
                this.emitFile({
                    type: "asset",
                    fileName: outputPath,
                    source: fs.readFileSync(sourceFile)
                });
            }
        }
    };
}
