/**
 * Convert a Web Audio AudioBuffer to a WAV Blob.
 *
 * Supports:
 *  - mono or stereo
 *  - 16-bit PCM
 *
 * Usage:
 *     const blob = audioBufferToWav(audioBuffer);
 *
 * Generated by ChatGPT
 */
export default function audioBufferToWav(audioBuffer) {
    const numChannels = audioBuffer.numberOfChannels;
    const sampleRate = audioBuffer.sampleRate;
    const numFrames = audioBuffer.length;

    const bytesPerSample = 2;
    const blockAlign = numChannels * bytesPerSample;
    const byteRate = sampleRate * blockAlign;
    const dataSize = numFrames * blockAlign;

    const buffer = new ArrayBuffer(44 + dataSize);
    const view = new DataView(buffer);

    let offset = 0;

    function writeString(s) {
        for (let i = 0; i < s.length; i++) {
            view.setUint8(offset++, s.charCodeAt(i));
        }
    }

    // RIFF header
    writeString("RIFF");
    view.setUint32(offset, 36 + dataSize, true); offset += 4;
    writeString("WAVE");

    // fmt chunk
    writeString("fmt ");
    view.setUint32(offset, 16, true); offset += 4;      // chunk size
    view.setUint16(offset, 1, true); offset += 2;       // PCM
    view.setUint16(offset, numChannels, true); offset += 2;
    view.setUint32(offset, sampleRate, true); offset += 4;
    view.setUint32(offset, byteRate, true); offset += 4;
    view.setUint16(offset, blockAlign, true); offset += 2;
    view.setUint16(offset, 16, true); offset += 2;      // bits/sample

    // data chunk
    writeString("data");
    view.setUint32(offset, dataSize, true); offset += 4;

    // Interleave samples
    const channels = [];
    for (let c = 0; c < numChannels; c++) {
        channels.push(audioBuffer.getChannelData(c));
    }

    for (let i = 0; i < numFrames; i++) {
        for (let c = 0; c < numChannels; c++) {
            let sample = channels[c][i];

            // Clamp to [-1, 1]
            sample = Math.max(-1, Math.min(1, sample));

            // Convert float -> signed 16-bit
            const pcm = sample < 0
                ? sample * 0x8000
                : sample * 0x7FFF;

            view.setInt16(offset, pcm, true);
            offset += 2;
        }
    }

    return new Blob([buffer], { type: "audio/wav" });
}
