
// Function generated by ChatGPT to convert a web audio audionuffer to a wav blob
function audioBufferToWav(audioBuffer)
{
    const numChannels = audioBuffer.numberOfChannels;
    const sampleRate = audioBuffer.sampleRate;
    const numFrames = audioBuffer.length;

    const bytesPerSample = 2;
    const blockAlign = numChannels * bytesPerSample;
    const byteRate = sampleRate * blockAlign;
    const dataSize = numFrames * blockAlign;

    const buffer = new ArrayBuffer(44 + dataSize);
    const view = new DataView(buffer);

    let offset = 0;

    function writeString(s) {
        for (let i = 0; i < s.length; i++) {
            view.setUint8(offset++, s.charCodeAt(i));
        }
    }

    // RIFF header
    writeString("RIFF");
    view.setUint32(offset, 36 + dataSize, true); offset += 4;
    writeString("WAVE");

    // fmt chunk
    writeString("fmt ");
    view.setUint32(offset, 16, true); offset += 4;      // chunk size
    view.setUint16(offset, 1, true); offset += 2;       // PCM
    view.setUint16(offset, numChannels, true); offset += 2;
    view.setUint32(offset, sampleRate, true); offset += 4;
    view.setUint32(offset, byteRate, true); offset += 4;
    view.setUint16(offset, blockAlign, true); offset += 2;
    view.setUint16(offset, 16, true); offset += 2;      // bits/sample

    // data chunk
    writeString("data");
    view.setUint32(offset, dataSize, true); offset += 4;

    // Interleave samples
    const channels = [];
    for (let c = 0; c < numChannels; c++) {
        channels.push(audioBuffer.getChannelData(c));
    }

    for (let i = 0; i < numFrames; i++) {
        for (let c = 0; c < numChannels; c++) {
            let sample = channels[c][i];

            // Clamp to [-1, 1]
            sample = Math.max(-1, Math.min(1, sample));

            // Convert float -> signed 16-bit
            const pcm = sample < 0
                ? sample * 0x8000
                : sample * 0x7FFF;

            view.setInt16(offset, pcm, true);
            offset += 2;
        }
    }

    return new Blob([buffer], { type: "audio/wav" });
}


// Play the sounds that we want to play
function playSounds(Tone, whatToPlay, tempo)
{
    // Determine the length of a beat
    const beat = 60. / tempo;

    // Create a synth and connect it to the main output
    const synth = new Tone.PolySynth().toDestination();

    // Play notes
    let t = 0;
    for (const notes of whatToPlay)
    {
        if (notes.length > 0)
        {
            synth.triggerAttackRelease(notes.map(note => Tone.Frequency(note, "midi")), 1. * beat, t);
        }
        t += 1. * beat;
    }
}


async function getAudioBuffer(whatToPlay, tempo)
{
    const Tone = await import("tone");
    const duration = whatToPlay.length * 60 / tempo;
    const audioBuffer = await Tone.Offline(async () => {
        playSounds(Tone, whatToPlay, tempo);
    }, duration);
    return audioBuffer;
}


export default async function generateWav(whatToPlay, tempo)
{
    const audioBuffer = await getAudioBuffer(whatToPlay, tempo);
    const blob = audioBufferToWav(audioBuffer);
    return blob;
}
