import * as Tone from "tone";
import { MusicalSequence, getDuration } from "../model/MusicalSequence";

interface WavEncodableAudioBuffer {
    readonly numberOfChannels: number;
    readonly sampleRate: number;
    readonly length: number;
    getChannelData(channel: number): Float32Array;
}


// Convert a Web Audio-compatible buffer to a 16-bit PCM WAV blob
// (function generated by ChatGPT)
function audioBufferToWav(audioBuffer: WavEncodableAudioBuffer): Blob
{
    const numChannels = audioBuffer.numberOfChannels;
    const sampleRate = audioBuffer.sampleRate;
    const numFrames = audioBuffer.length;

    const bytesPerSample = 2;
    const blockAlign = numChannels * bytesPerSample;
    const byteRate = sampleRate * blockAlign;
    const dataSize = numFrames * blockAlign;

    const buffer = new ArrayBuffer(44 + dataSize);
    const view = new DataView(buffer);

    let offset = 0;

    function writeString(value: string): void {
        for (let i = 0; i < value.length; i++) {
            view.setUint8(offset++, value.charCodeAt(i));
        }
    }

    // RIFF header
    writeString("RIFF");
    view.setUint32(offset, 36 + dataSize, true); offset += 4;
    writeString("WAVE");

    // fmt chunk
    writeString("fmt ");
    view.setUint32(offset, 16, true); offset += 4;      // chunk size
    view.setUint16(offset, 1, true); offset += 2;       // PCM
    view.setUint16(offset, numChannels, true); offset += 2;
    view.setUint32(offset, sampleRate, true); offset += 4;
    view.setUint32(offset, byteRate, true); offset += 4;
    view.setUint16(offset, blockAlign, true); offset += 2;
    view.setUint16(offset, 16, true); offset += 2;      // bits/sample

    // data chunk
    writeString("data");
    view.setUint32(offset, dataSize, true); offset += 4;

    // Interleave samples
    const channels: Float32Array[] = [];
    for (let c = 0; c < numChannels; c++) {
        channels.push(audioBuffer.getChannelData(c));
    }

    for (let i = 0; i < numFrames; i++) {
        for (let c = 0; c < numChannels; c++) {
            // The AudioBuffer contract guarantees one channel array per channel and one sample per frame
            // Since both loops use those exact bounds, neither indexed access can be undefined
            let sample = channels[c]![i]!;

            // Clamp to [-1, 1]
            sample = Math.max(-1, Math.min(1, sample));

            // Convert float -> signed 16-bit
            const pcm = sample < 0
                ? sample * 0x8000
                : sample * 0x7FFF;

            view.setInt16(offset, pcm, true);
            offset += 2;
        }
    }

    return new Blob([buffer], { type: "audio/wav" });
}


// Play the sounds that we want to play
async function playSounds(sequence: MusicalSequence, tempo: number): Promise<void>
{
    // Determine the length of a beat
    const beat = 60. / tempo;

    // Create a piano and connect it to the main output
    const piano = new Tone.Sampler({
        urls: {
            "A0" : "piano/A0v3.ogg",
            "C1" : "piano/C1v3.ogg",
            "D#1": "piano/Dsharp1v3.ogg",
            "F#1": "piano/Fsharp1v3.ogg",
            "A1" : "piano/A1v3.ogg",
            "C2" : "piano/C2v3.ogg",
            "D#2": "piano/Dsharp2v3.ogg",
            "F#2": "piano/Fsharp2v3.ogg",
            "A2" : "piano/A2v3.ogg",
            "C3" : "piano/C3v3.ogg",
            "D#3": "piano/Dsharp3v3.ogg",
            "F#3": "piano/Fsharp3v3.ogg",
            "A3" : "piano/A3v3.ogg",
            "C4" : "piano/C4v3.ogg",
            "D#4": "piano/Dsharp4v3.ogg",
            "F#4": "piano/Fsharp4v3.ogg",
            "A4" : "piano/A4v3.ogg",
            "C5" : "piano/C5v3.ogg",
            "D#5": "piano/Dsharp5v3.ogg",
            "F#5": "piano/Fsharp5v3.ogg",
            "A5" : "piano/A5v3.ogg",
            "C6" : "piano/C6v3.ogg",
            "D#6": "piano/Dsharp6v3.ogg",
            "F#6": "piano/Fsharp6v3.ogg",
            "A6" : "piano/A6v3.ogg",
            "C7" : "piano/C7v3.ogg",
            "D#7": "piano/Dsharp7v3.ogg",
            "F#7": "piano/Fsharp7v3.ogg",
            "A7" : "piano/A7v3.ogg",
            "C8" : "piano/C8v3.ogg"
        }
    }).toDestination();

    // Wait for all of Tone's buffer loads to complete
    // (and in particular for samples to be loaded)
    await Tone.loaded();

    // Set the volume (default is too low)
    piano.volume.value = 12;

    // Play notes
    let t = 0;
    for (const timedNote of sequence)
    {
        if (timedNote.note !== null)
        {
            piano.triggerAttackRelease(
                Tone.Frequency(timedNote.note, "midi").toNote(),
                timedNote.duration * beat,
                t,
            );
        }
        t += timedNote.duration * beat;
    }
}


// Generate an audio buffer of the sounds we want to play
async function getAudioBuffer(sequence: MusicalSequence, tempo: number): Promise<Tone.ToneAudioBuffer>
{
    // Wait for the ToneJS module to start
    // (not really necessary for offline generation, but let's keep it)
    await Tone.start();

    // Generate buffer
    const duration = getDuration(sequence) * 60 / tempo;
    const audioBuffer = await Tone.Offline(async () => {
        await playSounds(sequence, tempo);
    }, duration);
    return audioBuffer;
}


// Generate a 16-bit PCM WAV blob of the sounds we want to play
export async function generateWav(
    sequence: MusicalSequence,
    tempo: number,
): Promise<Blob>
{
    const audioBuffer = await getAudioBuffer(sequence, tempo);
    const blob = audioBufferToWav(audioBuffer);
    return blob;
}
